function auStyle = augraphicsstyle(varargin)
% AUGRAPHICSSTYLE   Aarhus University colour palette and plot style

   auStyle.colours.blue           = [  0/255,  61/255, 115/255]; % AU Blue
   auStyle.colours.red            = [225/255,   0/255,  26/255]; % AU Red
   auStyle.colours.green          = [139/255, 173/255,  63/255]; % AU Green
   auStyle.colours.turkish        = [  0/255, 171/255, 174/255]; % AU Turkish
   auStyle.colours.orange         = [238/255, 127/255,   0/255]; % AU Orange
   auStyle.colours.cyan           = [ 55/255, 160/255, 203/255]; % AU Cyan
   auStyle.colours.magenta        = [226/255,   0/255, 122/255]; % AU Magenta
   auStyle.colours.gold           = [250/255, 187/255,   0/255]; % AU Gold
   auStyle.colours.lilla          = [101/255,  90/255, 159/255]; % AU Lilla
   auStyle.colours.gray           = [135/255, 135/255, 135/255]; % AU Gray
   auStyle.colours.darkgray       = [ 75/255,  75/255,  74/255]; % AU Dark Gray
   auStyle.colours.darkcyan       = [  0/255,  62/255,  92/255]; % AU Dark Cyan
   auStyle.colours.darkblue       = [  0/255,  37/255,  70/255]; % AU Dark Blue
   auStyle.colours.darkgreen      = [ 50/255,  88/255,  33/255]; % AU Dark Green
   auStyle.colours.darkgold       = [ 99/255,  75/255,   3/255]; % AU Dark Gold
   auStyle.colours.darklilla      = [ 40/255,  28/255,  65/255]; % AU Dark Lilla
   auStyle.colours.darkturkish    = [  0/255,  69/255,  67/255]; % AU Dark Turkish
   auStyle.colours.darkorange     = [ 95/255,  52/255,   8/255]; % AU Dark Orange
   auStyle.colours.darkred        = [ 91/255,  12/255,  12/255]; % AU Dark Red
   auStyle.colours.darkmagenta    = [ 95/255,   0/255,  48/255]; % AU Dark Magenta
   auStyle.colours.backgroundgray = [247/255, 247/255, 244/255]; % AU Background Gray

   set(groot, ...
       'defaultFigureUnits', 'centimeters', ...
       'defaultFigurePosition', [0 0 2*20 2*20/(3/2*1.414)], ...
       'defaultFigurePaperUnits', 'centimeters', ...
       'defaultFigurePaperPositionMode', 'manual', ...
       'defaultFigurePaperSize', [2*20 2*20/(3/2*1.414)], ...
       'defaultTiledlayoutTileSpacing', 'compact', ...
       'defaultLineLineWidth', 1.25, ...
       'defaultAxesLineWidth', 0.75, ...
       'defaultTextFontSize', 12, ...
       'defaultAxesFontSize', 12, ...
       'defaultAxesFontName', 'Helvetica', ...
       'defaultAxesFontWeight', 'normal', ...
       'defaultAxesTitleFontWeight', 'bold', ...
       'defaultLegendFontName', 'Helvetica', ...
       'defaultLegendLocation', 'southeast', ...
       'defaultLegendOrientation', 'horizontal', ...
       'defaultAxesXGrid', 'on', ...
       'defaultAxesYGrid', 'on', ...
       'defaultAxesXMinorGrid', 'on', ...
       'defaultAxesXMinorGridMode', 'manual', ...
       'defaultAxesXMinorTick', 'on', ...
       'defaultAxesYMinorGrid', 'on', ...
       'defaultAxesYMinorGridMode', 'manual', ...
       'defaultAxesYMinorTick', 'on', ...
       'defaultAxesColorOrder', [ ...
           auStyle.colours.blue; ...
           auStyle.colours.red; ...
           auStyle.colours.green; ...
           auStyle.colours.turkish; ...
           auStyle.colours.orange; ...
           auStyle.colours.cyan; ...
           auStyle.colours.magenta; ...
           auStyle.colours.gold; ...
           auStyle.colours.lilla; ...
           auStyle.colours.gray; ...
           auStyle.colours.darkgray; ...
           auStyle.colours.darkcyan; ...
           auStyle.colours.darkblue; ...
           auStyle.colours.darkgreen; ...
           auStyle.colours.darkgold; ...
           auStyle.colours.darklilla; ...
           auStyle.colours.darkturkish; ...
           auStyle.colours.darkorange; ...
           auStyle.colours.darkred; ...
           auStyle.colours.darkmagenta; ...
       ] ...
   )

   if nargin ~= 0
      figure('Name', 'Aarhus University MATLAB Colour Template')
      colors = colororder;
      colors_n = length(colors);
      t = 0:1e-2:2*pi;
      hold on
      for i = 1:colors_n
          plot(t, sin(t+1+i*(colors_n/(pi))))
      end
      hold off
      xlim([0 2*pi])
      title('AU Color Scheme')
      legend( ...
          'AU Blue', ...
          'AU Orange', ...
          'AU Red', ...
          'AU Green', ...
          'AU Magenta', ...
          'AU Lilla', ...
          'AU Cyan', ...
          'AU Turkish', ...
          'AU Gold', ...
          'AU Gray', ...
          'AU Dark Gray', ...
          'AU Dark Cyan', ...
          'AU Dark Blue', ...
          'AU Dark Green', ...
          'AU Dark Gold', ...
          'AU Dark Lilla', ...
          'AU Dark Turkish', ...
          'AU Dark Orange', ...
          'AU Dark Red', ...
          'AU Dark Magenta', ...
          'Location', 'westoutside', ...
          'Orientation', 'vertical' ...
      )
   end
end